---
name: PR Build
on:
  workflow_run:
    workflows: ["Build Branch On Push"]
    types: [completed]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  maven_build:
    name: Build maven
    uses: ./.github/workflows/wf-push-build.yml

  run_sonar_scan:
    name: Run Sonar Scan
    runs-on: ubuntu-latest
    needs: maven_build
    steps:
      - name: echo stuff
        run: echo hello world
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e  # v5.1.0
        with:
          distribution: "temurin"
          java-package: "jdk"
          java-version: "21"
          overwrite-settings: "false"
      - name: Cache SonarQube packages
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: echo stuff
        run:
          echo ${{ github.event.workflow_run.id }}
      - name: Download artifacts
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.
        with:
          name: build-artifacts
          path: ./
          github-token: ${{ secrets.GITHUB_TOKEN }}
#           run-id: ${{ github.event.workflow_run.id }}
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: bash
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dstyle.color=always \
            --no-transfer-progress
