---
name: Validate Reonvate config
on: pull_request
jobs:
  pr-renovate-validate:
    name: Renovate
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd  # v5.0.1
      - name: Renovate config validator
        run: >
          docker run --rm -v "$(pwd):/usr/src/app" renovate/renovate renovate-config-validator
