---
name: Validate Renovate config
on: pull_request
jobs:
  pr-renovate-validate:
    name: Renovate
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
      - name: Renovate config validator
        run: >
          docker run --rm -v "$(pwd):/usr/src/app" renovate/renovate renovate-config-validator
