---
name: Build Branch On Push
on:
  push:
    branches:
      - '**'
  workflow_call:
jobs:
  build:
    name: Maven build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Setup Java
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93  # v4.0.0
        with:
          distribution: "temurin"
          java-package: "jdk"
          java-version: "21"
          overwrite-settings: "false"
      - name: Set up Maven
        uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
        with:
          maven-version: 3.9.12
      - name: Maven build
        run: |
          mvn -B clean install -Dstyle.color=always --no-transfer-progress
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v 6.0.0
        if: always()
        with:
          name: build-artifacts
          path: '**/target/*'
      - name: Test Report
        if: always()
        uses: dorny/test-reporter@fe45e9537387dac839af0d33ba56eed8e24189e8 # v2.3.0
        with:
          name: Maven Tests
          path: '**/target/surefire-reports/TEST-*.xml'
          reporter: java-junit
