---
name: Run Renovate Bot
on:
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - main
  schedule:
    - cron: "42 */8 * * *"  # Run Renovate every 8th hour
jobs:
  renovate-bot:
    name: Renovate
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 30
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2
        id: app-token
        with:
          app-id: ${{ vars.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

      - name: Run Renovate
        uses: renovatebot/github-action@f7fad228a053c69a98e24f8e4f6cf40db8f61e08  # v44.2.1
        env:
          RENOVATE_GIT_AUTHOR: "Renovate Bot <renovate-bot@users.noreply.github.com>"
          RENOVATE_REPOSITORIES: '["wintersoftch/JavaCodeSnippets"]' # Or use RENOVATE_AUTODISCOVER
          RENOVATE_TOKEN: ${{ steps.app-token.outputs.token }}