---
name: Run Renovate Bot
on:
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - main
  schedule:
    - cron: "42 */8 * * *"  # Run Renovate every 8th hour
jobs:
  renovate-bot:
    name: Renovate
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 30
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1
        id: app-token
        with:
          app-id: ${{ vars.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

      - name: Run Renovate
        uses: renovatebot/github-action@5712c6a41dea6cdf32c72d92a763bd417e6606aa  # v44.0.5
        env:
          RENOVATE_GIT_AUTHOR: "Renovate Bot <renovate-bot@users.noreply.github.com>"
          RENOVATE_REPOSITORIES: '["wintersoftch/JavaCodeSnippets"]' # Or use RENOVATE_AUTODISCOVER
          RENOVATE_TOKEN: ${{ steps.app-token.outputs.token }}