---
name: Build Branch On Push
on:
  push:
    branches:
      - '**'
  workflow_call:
jobs:
  build:
    name: Maven build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup Java
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e  # v5.1.0
        with:
          distribution: "temurin"
          java-package: "jdk"
          java-version: "21"
          overwrite-settings: "false"
      - name: Set up Maven
        uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
        with:
          maven-version: 3.9.12
      - name: Maven build
        run: |
          mvn -B clean install -Dstyle.color=always --no-transfer-progress
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v 6.0.0
        if: always()
        with:
          name: build-artifacts
          path: '**/target/*'
      - name: Test Report
        if: always()
        uses: dorny/test-reporter@e17be7e0078fc00f61965f3b4032f1e1fdc7fcfb # v2.4.0
        with:
          name: Maven Tests
          path: '**/target/surefire-reports/TEST-*.xml'
          reporter: java-junit
